### ISSUE TITLE
RestOptions cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by ThomsonIT** [sean7512/RestEssentials#1]
Hi,

i presumably found a bug with the RestOptions struct. It seems that with Swift 2.0 i cannot initialize the Struct in my on class as there is no init method found.

adding "public init() {}" to the end of the struct fixes the error. Pull request follows.

**Comment by sean7512** [comment]
Thank you very much for the fix!  I have merged into master and released 1.0.1 to cocoapods.

Enjoy!
