### ISSUE TITLE
'raw' is inaccessible due to 'private' protection level in JSON.swift

### ISSUE THREAD

**Issue by mabdullah2010** [sean7512/RestEssentials#18]
When trying to build a project including RestEssentials, I receive the following error in JSON.swift:

> 'raw' is inaccessible due to 'private' protection level

The makeData() function inside of the internal extension for the JSON struct is trying to access a private variable 'raw'. If the variable is changed to be fileprivate instead, it compiles successfully. Do you believe anything else needs to be changed to address this?

Thanks

**Comment by sean7512** [comment]
You are not using Swift 4. See this already closed issue: https://github.com/sean7512/RestEssentials/issues/14

**Comment by mabdullah2010** [comment]
@sean7512 Thank you for your quick response and my apologies for not noticing that you had already addressed this question in a previous issue. This can be marked as resolved. Thanks!

**Comment by sean7512** [comment]
I'll leave it open until I get clarification that solution works for you as well...please let me know if that solves your issue.

**Comment by mabdullah2010** [comment]
I just tried building the project again and the solution indeed works for me. Thank you!

**Comment by sean7512** [comment]
Ok, great! Thanks for the confirmation...closing now.
