### ISSUE TITLE
Can't disable the on finish console logging

### ISSUE THREAD

**Issue by hanssl** [sean7512/RestEssentials#20]
I see the 'req.skipRequestLog' flag in the request-logger.js file.  If this were changed to 'options.skipRequestLog' then the console output could be silenced when the object is instantiated.

**Comment by sean7512** [comment]
Did you open this issue my mistake?

**Comment by sean7512** [comment]
By mistake* (autocorrect issues)

**Comment by sean7512** [comment]
Closing since this issue was opened erroneously against the wrong project.
