### ISSUE TITLE
Help configuring App Transport Security

### ISSUE THREAD

**Issue by ricardo-vallejo** [sean7512/RestEssentials#23]
Hello

I'm new with Swift and I don't know how to configure the App Transport Security. I'm using iOS 9 and when I run the test I don't get any response from the API.

Thanks

**Comment by sean7512** [comment]
Is your endpoint not using SSL or does it not conform to the requirements for App Transport Security?

You'll need to edit the app's Info.plist to allow non-ssl connectionist o your host. See https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity?language=objc
