### ISSUE TITLE
Pod install errro "SWIFT_VERSION"

### ISSUE THREAD

**Issue by JuanSeBestia** [sean7512/RestEssentials#25]
Hi i'm working with Swift 4, without flag use_frameworks!, and have this error

pod install
```
Installing RestEssentials (4.0.2)
[!] Unable to determine Swift version for the following pods:

- `RestEssentials` does not specify a Swift version and none of the targets (`SomeProjectTests`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by sean7512** [comment]
@JuanSeBestia As the error says, your project will need to set the SWIFT_VERSION in your target. That should do that

**Comment by sean7512** [comment]
@JuanSeBestia Please use 5.0.1 which should address this issue and use Swift Package Manager or Cocoapods.
